# Generated by Django 3.2.16 on 2023-02-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20230131_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='code',
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(default='€', max_length=10),
        ),
    ]
